import React, { createContext, useContext, useState, useEffect } from "react";

export const SUPPORTED_LANGUAGES = [
  {
    id: "en",
    name: "English",
    englishName: "English",
    region: "Global Standard",
    flag: "🇬🇧",
    sub: "Default Corporate Language",
  },
  {
    id: "hi",
    name: "हिन्दी",
    englishName: "Hindi",
    region: "भारत / North & Central",
    flag: "🇮🇳",
    sub: "राष्ट्रीय भाषा (National Language)",
  },
  {
    id: "mr",
    name: "मराठी",
    englishName: "Marathi",
    region: "महाराष्ट्र (Maharashtra)",
    flag: "🚩",
    sub: "मुंबई व पुणे व्यापारी मंडळ",
  },
  {
    id: "gu",
    name: "ગુજરાતી",
    englishName: "Gujarati",
    region: "ગુજરાત (Gujarat)",
    flag: "🦁",
    sub: "વેપાર અને ઉત્પાદન હબ (Trade Hub)",
  },
  {
    id: "ta",
    name: "தமிழ்",
    englishName: "Tamil",
    region: "தமிழ்நாடு (Tamil Nadu)",
    flag: "🏛️",
    sub: "சென்னை & கோவை தொழில் மண்டலம்",
  },
  {
    id: "te",
    name: "తెలుగు",
    englishName: "Telugu",
    region: "ఆంధ్ర & తెలంగాణ (AP & TS)",
    flag: "⚡",
    sub: "హైదరాబాద్ & విశాఖపట్నం వాణిజ్యం",
  },
  {
    id: "kn",
    name: "ಕನ್ನಡ",
    englishName: "Kannada",
    region: "ಕರ್ನಾಟಕ (Karnataka)",
    flag: "🌾",
    sub: "ಬೆಂಗಳೂರು ಉದ್ಯಮ & ತಂತ್ರಜ್ಞಾನ",
  },
  {
    id: "bn",
    name: "বাংলা",
    englishName: "Bengali",
    region: "পশ্চিমবঙ্গ (West Bengal)",
    flag: "🎨",
    sub: "কলকাতা ও পূর্ব ভারত বাণিজ্য",
  },
  {
    id: "pa",
    name: "ਪੰਜਾਬੀ",
    englishName: "Punjabi",
    region: "ਪੰਜਾਬ (Punjab)",
    flag: "🚜",
    sub: "ਖੇਤੀਬਾੜੀ ਅਤੇ ਐਮਐਸਐਮਈ ਵਪਾਰ",
  },
  {
    id: "ml",
    name: "മലയാളം",
    englishName: "Malayalam",
    region: "കേരളം (Kerala)",
    flag: "🌴",
    sub: "കൊച്ചി വ്യവസായവും വിദേശ വാണിജ്യവും",
  },
  {
    id: "or",
    name: "ଓଡ଼ିଆ",
    englishName: "Odia",
    region: "ଓଡ଼ିଶା (Odisha)",
    flag: "🐚",
    sub: "ଖଣି, ଇସ୍ପାତ ଏବଂ ଏମଏସଏମଇ ବାଣିଜ୍ୟ",
  },
  {
    id: "as",
    name: "অসমীয়া",
    englishName: "Assamese",
    region: "অসম (Assam & NE)",
    flag: "🍵",
    sub: "চাহ, তেল আৰু উত্তৰ-পূব বাণিজ্য",
  },
  {
    id: "ur",
    name: "اردو",
    englishName: "Urdu",
    region: "قومی تجارتی مراکز (Pan-India)",
    flag: "🌙",
    sub: "دہلی، حیدرآباد، لکھنؤ و کشمیر تجارت",
  },
  {
    id: "bho",
    name: "भोजपुरी",
    englishName: "Bhojpuri",
    region: "बिहार व पूर्वांचल (Bihar & UP)",
    flag: "🪷",
    sub: "कृषि, मंडी व एमएसएमई व्यापार",
  },
  {
    id: "mai",
    name: "मैथिली",
    englishName: "Maithili",
    region: "मिथिलांचल (Mithila Region)",
    flag: "🪔",
    sub: "उद्योग, हस्तशिल्प एवं व्यापार",
  },
  {
    id: "kok",
    name: "कोंकणी",
    englishName: "Konkani",
    region: "गोवा आणि कोकण (Goa & Coastal)",
    flag: "🏖️",
    sub: "सागरी व्यापार, पर्यटन व एमएसएमई",
  },
  {
    id: "sd",
    name: "سنڌي / सिंधी",
    englishName: "Sindhi",
    region: "سندھی واپاري (Merchant Network)",
    flag: "🪢",
    sub: "અખિલ ભારતીય સિંધી વેપારી સમુદાય",
  },
  {
    id: "ne",
    name: "नेपाली",
    englishName: "Nepali",
    region: "सिक्किम र पहाडी व्यापार (Sikkim & Hills)",
    flag: "🏔️",
    sub: "पर्यटन, कृषि र हिमाली व्यापार",
  },
];

const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard",
    cashFlow: "Cash Flow Twin",
    invoices: "Invoices",
    expenses: "Expenses & Burn",
    customers: "Customers & Risk",
    forecast: "90-Day Forecast",
    simulator: "What-If Simulator",
    financing: "MSME Financing",
    gst: "GST & Tax",
    payroll: "Workers & Payroll",
    reports: "Financial Reports",
    settings: "Settings",
    logout: "Logout",
    quickAdd: "Quick Add",
    quickSearch: "Quick search...",
    askAi: "Ask FinTwin",
    notifications: "Notifications",
    liquidCash: "Liquid Cash Reserve",
    receivables: "Outstanding Receivables",
    burnRate: "Monthly Burn Velocity",
    netRunway: "30-Day Net Runway",
    daysBuffer: "Days Buffer",
    pendingInvoices: "Pending Invoices",
    solvencyScore: "Solvency Health Score",
    saveChanges: "Save Changes",
    companyProfile: "Company Profile & Financial Targets",
    languageOption: "Regional Language & Localization",
    languageSub: "Choose your preferred Indian regional language for financial dashboards & reports",
    currentLanguage: "Current Active Language",
    selectLanguage: "Select Regional Language",
    saveLanguage: "Apply Language",
    resetData: "Clear & Reset Financial Data",
    activeTwin: "Active Twin Engine",
    days: "Days",
  },
  hi: {
    dashboard: "डैशबोर्ड",
    cashFlow: "कैश फ्लो ट्विन",
    invoices: "चालान / बिल (Invoices)",
    expenses: "खर्च व मासिक बर्न",
    customers: "ग्राहक व जोखिम विश्लेषण",
    forecast: "90-दिवसीय पूर्वानुमान",
    simulator: "शॉक सिमुलेटर (What-If)",
    financing: "एमएसएमई वित्तपोषण (Loans)",
    gst: "जीएसटी एवं टैक्स (GST)",
    payroll: "कर्मचारी व वेतन (Payroll)",
    reports: "वित्तीय रिपोर्ट",
    settings: "सेटिंग्स (Settings)",
    logout: "लॉग आउट",
    quickAdd: "+ त्वरित जोड़ें",
    quickSearch: "त्वरित खोजें...",
    askAi: "एआई से पूछें (AI Twin)",
    notifications: "सूचनाएं एवं अलर्ट",
    liquidCash: "उपलब्ध नकद राशि (Liquid Cash)",
    receivables: "बकाया वसूली (Receivables)",
    burnRate: "मासिक खर्च गति (Burn Rate)",
    netRunway: "30-दिवसीय शुद्ध रनवे",
    daysBuffer: "दिनों का नकद बफर",
    pendingInvoices: "लंबित चालान",
    solvencyScore: "सॉल्वेंसी स्वास्थ्य स्कोर",
    saveChanges: "परिवर्तन सहेजें",
    companyProfile: "कंपनी प्रोफ़ाइल एवं वित्तीय लक्ष्य",
    languageOption: "क्षेत्रीय भाषा एवं स्थानीयकरण",
    languageSub: "वित्तीय डैशबोर्ड और रिपोर्ट के लिए अपनी पसंदीदा भारतीय भाषा चुनें",
    currentLanguage: "वर्तमान सक्रिय भाषा",
    selectLanguage: "क्षेत्रीय भाषा चुनें",
    saveLanguage: "भाषा लागू करें",
    resetData: "वित्तीय डेटा रीसेट करें",
    activeTwin: "सक्रिय ट्विन इंजन",
    days: "दिन",
  },
  mr: {
    dashboard: "डॅशबोर्ड",
    cashFlow: "कॅश फ्लो ट्विन",
    invoices: "बिले व इनव्हॉइस",
    expenses: "मासिक खर्च व बर्न",
    customers: "ग्राहक व जोखीम",
    forecast: "90-दिवसीय अंदाज",
    simulator: "शॉक सिम्युलेटर",
    financing: "एमएसएमई कर्ज व फायनान्स",
    gst: "जीएसटी व कर प्रणाली",
    payroll: "कर्मचारी व वेतन (Payroll)",
    reports: "आर्थिक अहवाल",
    settings: "सेटिंग्ज (Settings)",
    logout: "बाहेर पडा (Logout)",
    quickAdd: "+ त्वरित जोडा",
    quickSearch: "शोधा...",
    askAi: "एआय ला विचारा",
    notifications: "सूचना व अलर्ट",
    liquidCash: "उपलब्ध रोख शिल्लक",
    receivables: "येणे बाकी रक्कम",
    burnRate: "मासिक खर्च गती",
    netRunway: "30-दिवसीय रनवे",
    daysBuffer: "दिवसांचा बफर",
    pendingInvoices: "प्रलंबित बिले",
    solvencyScore: "आर्थिक आरोग्य स्कोर",
    saveChanges: "बदल जतन करा",
    companyProfile: "कंपनी तपशील व आर्थिक उद्दिष्टे",
    languageOption: "प्रादेशिक भाषा निवड",
    languageSub: "डॅशबोर्ड आणि अहवालांसाठी तुमची प्रादेशिक भाषा निवडा",
    currentLanguage: "सध्याची सक्रिय भाषा",
    selectLanguage: "प्रादेशिक भाषा निवडा",
    saveLanguage: "भाषा लागू करा",
    resetData: "सर्व डेटा रिसेट करा",
    activeTwin: "सक्रिय डिजिटल ट्विन",
    days: "दिवस",
  },
  gu: {
    dashboard: "ડેશબોર્ડ",
    cashFlow: "કેશ ફ્લો ટ્વિન",
    invoices: "બિલ અને ઇનવોઇસ",
    expenses: "માસિક ખર્ચ અને બર્ન",
    customers: "ગ્રાહકો અને જોખમ",
    forecast: "90-દિવસીય અંદાજ",
    simulator: "શોક સિમ્યુલેટર",
    financing: "MSME ધિરાણ અને લોન",
    gst: "જીએસટી અને કર (GST)",
    payroll: "કર્મચારી અને પગાર (Payroll)",
    reports: "નાણાકીય અહેવાલો",
    settings: "સેટિંગ્સ",
    logout: "લૉગ આઉટ",
    quickAdd: "+ ઝડપી ઉમેરો",
    quickSearch: "શોધો...",
    askAi: "AI ને પૂછો",
    notifications: "સૂચનાઓ અને ચેતવણીઓ",
    liquidCash: "હાજર રોકડ અનામત",
    receivables: "બાકી લેણી રકમ",
    burnRate: "માસિક ખર્ચ ગતિ",
    netRunway: "30-દિવસીય રનવે",
    daysBuffer: "દિવસોનો કેશ બફર",
    pendingInvoices: "બાકી બિલો",
    solvencyScore: "નાણાકીય આરોગ્ય સ્કોર",
    saveChanges: "ફેરફારો સાચવો",
    companyProfile: "કંપની પ્રોફાઇલ અને લક્ષ્યો",
    languageOption: "પ્રાદેશિક ભાષા પસંદગી",
    languageSub: "નાણાકીય ડેશબોર્ડ માટે તમારી મનપસંદ પ્રાદેશિક ભાષા પસંદ કરો",
    currentLanguage: "વર્તમાન સક્રિય ભાષા",
    selectLanguage: "પ્રાદેશિક ભાષા પસંદ કરો",
    saveLanguage: "ભાષા લાગુ કરો",
    resetData: "ડેટા રીસેટ કરો",
    activeTwin: "સક્રિય ટ્વિન એન્જિન",
    days: "દિવસ",
  },
  ta: {
    dashboard: "முகப்புப்பலகை (Dashboard)",
    cashFlow: "பணப்புழக்க ட்வின்",
    invoices: "விலைப்பட்டியல்கள் (Invoices)",
    expenses: "செலவுகள் & மாதாந்திர பர்ன்",
    customers: "வாடிக்கையாளர்கள் & ஆபத்து",
    forecast: "90-நாள் முன்னறிவிப்பு",
    simulator: "ஷாக் சிமுலேட்டர்",
    financing: "MSME நிதி உதவி (Loans)",
    gst: "ஜிஎஸ்டி & வரி (GST)",
    payroll: "பணியாளர்கள் & ஊதியம்",
    reports: "நிதி அறிக்கைகள்",
    settings: "அமைப்புகள் (Settings)",
    logout: "வெளியேறு (Logout)",
    quickAdd: "+ விரைவு சேர்",
    quickSearch: "தேடுக...",
    askAi: "AI-யிடம் கேட்கவும்",
    notifications: "அறிவிப்புகள்",
    liquidCash: "இருப்பு ரொக்கம் (Liquid Cash)",
    receivables: "வரவேண்டிய தொகை",
    burnRate: "மாதாந்திர செலவு வேகம்",
    netRunway: "30-நாள் நிகர ரன்வே",
    daysBuffer: "நாட்கள் பாதுகாப்பு",
    pendingInvoices: "நிலுவையில் உள்ள பில்கள்",
    solvencyScore: "நிதி ஆரோக்கிய மதிப்பீடு",
    saveChanges: "சேமிக்கவும்",
    companyProfile: "நிறுவன விவரங்கள் & இலக்குகள்",
    languageOption: "வட்டார மொழி தேர்வு",
    languageSub: "நிதி டாஷ்போர்டுக்கான உங்கள் பிராந்திய மொழியைத் தேர்ந்தெடுக்கவும்",
    currentLanguage: "செயலில் உள்ள மொழி",
    selectLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",
    saveLanguage: "மொழியைப் பயன்படுத்து",
    resetData: "தரவை மீட்டமைக்கவும்",
    activeTwin: "செயலில் உள்ள ட்வின்",
    days: "நாட்கள்",
  },
  te: {
    dashboard: "డ్యాష్‌బోర్డ్",
    cashFlow: "నగదు ప్రవాహ ట్విన్",
    invoices: "ఇన్వాయిస్‌లు (Invoices)",
    expenses: "ఖర్చులు & నెలవారీ బర్న్",
    customers: "కస్టమర్లు & రిస్క్",
    forecast: "90-రోజుల అంచనా",
    simulator: "షాక్ సిమ్యులేటర్",
    financing: "MSME రుణాలు & ఫైనాన్సింగ్",
    gst: "జీఎస్టీ & పన్ను (GST)",
    payroll: "సిబ్బంది & జీతాలు (Payroll)",
    reports: "ఆర్థిక నివేదికలు",
    settings: "సెట్టింగ్‌లు",
    logout: "లాగ్ అవుట్",
    quickAdd: "+ త్వరిత జోడింపు",
    quickSearch: "శోధించండి...",
    askAi: "AI ని అడగండి",
    notifications: "నోటిఫికేషన్‌లు",
    liquidCash: "అందుబాటులో ఉన్న నగదు",
    receivables: "రావాల్సిన బాకీలు",
    burnRate: "నెలవారీ ఖర్చు వేగం",
    netRunway: "30-రోజుల రన్‌వే",
    daysBuffer: "రోజుల రక్షణ",
    pendingInvoices: "పెండింగ్ బిల్లులు",
    solvencyScore: "ఆర్థిక ఆరోగ్య స్కోరు",
    saveChanges: "మార్పులను సేవ్ చేయండి",
    companyProfile: "కంపెనీ వివరాలు & లక్ష్యాలు",
    languageOption: "ప్రాంతీయ భాష ఎంపిక",
    languageSub: "మీ ఆర్థిక డ్యాష్‌బోర్డ్ కోసం మీకు కావలసిన భాషను ఎంచుకోండి",
    currentLanguage: "ప్రస్తుత భాష",
    selectLanguage: "ప్రాంతీయ భాషను ఎంచుకోండి",
    saveLanguage: "భాషను వర్తింపజేయండి",
    resetData: "డేటాను రీసెట్ చేయండి",
    activeTwin: "క్రియాశీల ట్విన్",
    days: "రోజులు",
  },
  kn: {
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    cashFlow: "ಹಣಕಾಸು ಹರಿವು ಟ್ವಿನ್",
    invoices: "ಇನ್‌ವಾಯ್ಸ್‌ಗಳು (Invoices)",
    expenses: "ಖರ್ಚುಗಳು & ಬರ್ನ್",
    customers: "ಗ್ರಾಹಕರು & ಅಪಾಯ",
    forecast: "90-ದಿನಗಳ ಮುನ್ಸೂಚನೆ",
    simulator: "ಶಾಕ್ ಸಿಮ್ಯುಲೇಟರ್",
    financing: "MSME ಸಾಲ & ಹಣಕಾಸು",
    gst: "ಜಿಎಸ್ಟಿ & ತೆರಿಗೆ (GST)",
    payroll: "ನೌಕರರು & ವೇತನ (Payroll)",
    reports: "ಹಣಕಾಸು ವರದಿಗಳು",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    logout: "ಲಾಗ್ ಔಟ್",
    quickAdd: "+ ತ್ವರಿತ ಸೇರ್ಪಡೆ",
    quickSearch: "ಹುಡುಕಿ...",
    askAi: "AI ಅನ್ನು ಕೇಳಿ",
    notifications: "ಸೂಚನೆಗಳು & ಎಚ್ಚರಿಕೆಗಳು",
    liquidCash: "ಲಭ್ಯವಿರುವ ನಗದು ಮೀಸಲು",
    receivables: "ಬರಬೇಕಾದ ಬಾಕಿ ಹಣ",
    burnRate: "ಮಾಸಿಕ ವೆಚ್ಚದ ವೇಗ",
    netRunway: "30-ದಿನಗಳ ರನ್‌ವೇ",
    daysBuffer: "ದಿನಗಳ ರಕ್ಷಣೆ",
    pendingInvoices: "ಬಾಕಿ ಇರುವ ಇನ್‌ವಾಯ್ಸ್‌ಗಳು",
    solvencyScore: "ಆರ್ಥಿಕ ಆರೋಗ್ಯ ಸ್ಕೋರ್",
    saveChanges: "ಉಳಿಸಿ",
    companyProfile: "ಕಂಪನಿ ವಿವರಗಳು & ಗುರಿಗಳು",
    languageOption: "ಪ್ರಾದೇಶಿಕ ಭಾಷೆ ಆಯ್ಕೆ",
    languageSub: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗಾಗಿ ನಿಮ್ಮ ಮೆಚ್ಚಿನ ಪ್ರಾದೇಶಿಕ ಭಾಷೆಯನ್ನು ಆರಿಸಿ",
    currentLanguage: "ಸಕ್ರಿಯ ಭಾಷೆ",
    selectLanguage: "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    saveLanguage: "ಅನ್ವಯಿಸಿ",
    resetData: "ಡೇಟಾ ಮರುಹೊಂದಿಸಿ",
    activeTwin: "ಸಕ್ರಿಯ ಟ್ವಿನ್ ಎಂಜಿನ್",
    days: "ದಿನಗಳು",
  },
  bn: {
    dashboard: "ড্যাশবোর্ড",
    cashFlow: "ক্যাশ ফ্লো টুইন",
    invoices: "চালান ও বিল (Invoices)",
    expenses: "মাসিক খরচ ও বার্ন",
    customers: "গ্রাহক ও ঝুঁকি বিশ্লেষণ",
    forecast: "৯০-দিনের পূর্বাভাস",
    simulator: "শক সিমুলেটর",
    financing: "এমএসএমই ঋণ ও অর্থায়ন",
    gst: "জিএসটি ও ট্যাক্স (GST)",
    payroll: "কর্মী ও বেতন (Payroll)",
    reports: "আর্থিক প্রতিবেদন",
    settings: "সেটিংস",
    logout: "লগ আউট",
    quickAdd: "+ দ্রুত যোগ করুন",
    quickSearch: "অনুসন্ধান করুন...",
    askAi: "AI কে জিজ্ঞাসা করুন",
    notifications: "বিজ্ঞপ্তি ও সতর্কতা",
    liquidCash: "উপলব্ধ নগদ তহবিল",
    receivables: "বকেয়া পাওনা",
    burnRate: "মাসিক ব্যয়ের গতি",
    netRunway: "৩০-দিনের নেট রানওয়ে",
    daysBuffer: "দিনের বাফার",
    pendingInvoices: "মুলতুবি চালান",
    solvencyScore: "আর্থিক স্বাস্থ্য স্কোর",
    saveChanges: "পরিবর্তন সংরক্ষণ করুন",
    companyProfile: "কোম্পানি প্রোফাইল ও আর্থিক লক্ষ্য",
    languageOption: "আঞ্চলিক ভাষা নির্বাচন",
    languageSub: "ড্যাশবোর্ডের জন্য আপনার পছন্দের ভারতীয় আঞ্চলিক ভাষা নির্বাচন করুন",
    currentLanguage: "বর্তমান ভাষা",
    selectLanguage: "ভাষা নির্বাচন করুন",
    saveLanguage: "ভাষা প্রয়োগ করুন",
    resetData: "ডেটা রিসেট করুন",
    activeTwin: "সক্রিয় টুইন ইঞ্জিন",
    days: "দিন",
  },
  pa: {
    dashboard: "ਡੈਸ਼ਬੋਰਡ",
    cashFlow: "ਕੈਸ਼ ਫਲੋ ਟਵਿਨ",
    invoices: "ਬਿੱਲ ਅਤੇ ਇਨਵੌਇਸ",
    expenses: "ਮਹੀਨਾਵਾਰ ਖਰਚੇ ਅਤੇ ਬਰਨ",
    customers: "ਗਾਹਕ ਅਤੇ ਜੋਖਮ",
    forecast: "90-ਦਿਨਾਂ ਦਾ ਪੂਰਵ ਅਨੁਮਾਨ",
    simulator: "ਸ਼ੌਕ ਸਿਮੂਲੇਟਰ",
    financing: "ਐਮਐਸਐਮਈ ਕਰਜ਼ੇ ਅਤੇ ਵਿੱਤ",
    gst: "ਜੀਐਸਟੀ ਅਤੇ ਟੈਕਸ (GST)",
    payroll: "ਕਰਮਚਾਰੀ ਅਤੇ ਤਨਖਾਹ (Payroll)",
    reports: "ਵਿੱਤੀ ਰਿਪੋਰਟਾਂ",
    settings: "ਸੈਟਿੰਗਾਂ",
    logout: "ਲੌਗ ਆਉਟ",
    quickAdd: "+ ਤੁਰੰਤ ਜੋੜੋ",
    quickSearch: "ਖੋਜੋ...",
    askAi: "AI ਨੂੰ ਪੁੱਛੋ",
    notifications: "ਸੂਚਨਾਵਾਂ",
    liquidCash: "ਉਪਲਬਧ ਨਕਦ ਰਾਖਵਾਂ",
    receivables: "ਬਕਾਇਆ ਰਕਮ",
    burnRate: "ਮਹੀਨਾਵਾਰ ਖਰਚ ਗਤੀ",
    netRunway: "30-ਦਿਨਾਂ ਦਾ ਰਨਵੇ",
    daysBuffer: "ਦਿਨਾਂ ਦਾ ਬਫਰ",
    pendingInvoices: "ਬਕਾਇਆ ਬਿੱਲ",
    solvencyScore: "ਵਿੱਤੀ ਸਿਹਤ ਸਕੋਰ",
    saveChanges: "ਸੰਭਾਲੋ (Save)",
    companyProfile: "ਕੰਪਨੀ ਪ੍ਰੋਫਾਈਲ ਅਤੇ ਟੀਚੇ",
    languageOption: "ਖੇਤਰੀ ਭਾਸ਼ਾ ਚੋਣ",
    languageSub: "ਡੈਸ਼ਬੋਰਡ ਲਈ ਆਪਣੀ ਪਸੰਦੀਦਾ ਖੇਤਰੀ ਭਾਸ਼ਾ ਚੁਣੋ",
    currentLanguage: "ਮੌਜੂਦਾ ਭਾਸ਼ਾ",
    selectLanguage: "ਖੇਤਰੀ ਭਾਸ਼ਾ ਚੁਣੋ",
    saveLanguage: "ਭਾਸ਼ਾ ਲਾਗੂ ਕਰੋ",
    resetData: "ਸਾਰਾ ਡੇਟਾ ਰੀਸੈਟ ਕਰੋ",
    activeTwin: "ਸਰਗਰਮ ਟਵਿਨ",
    days: "ਦਿਨ",
  },
  ml: {
    dashboard: "ഡാഷ്‌ബോർഡ്",
    cashFlow: "ക്യാഷ് ഫ്ലോ ട്വിൻ",
    invoices: "ഇൻവോയ്സുകൾ & ബില്ലുകൾ",
    expenses: "ചെലവുകളും പ്രതിമാസ ബേണും",
    customers: "ഉപഭോക്താക്കളും റിസ്കും",
    forecast: "90-ദിവസത്തെ പ്രവചനം",
    simulator: "ഷോക്ക് സിമുലേറ്റർ",
    financing: "MSME വായ്പ & ധനസഹായം",
    gst: "ജിഎസ്ടി & നികുതി (GST)",
    payroll: "തൊഴിലാളികളും ശമ്പളവും (Payroll)",
    reports: "ധനകാര്യ റിപ്പോർട്ടുകൾ",
    settings: "ക്രമീകരണങ്ങൾ (Settings)",
    logout: "ലോഗ് ഔട്ട്",
    quickAdd: "+ വേഗത്തിൽ ചേർക്കുക",
    quickSearch: "തിരയുക...",
    askAi: "AI-യോട് ചോദിക്കുക",
    notifications: "അറിയിപ്പുകൾ",
    liquidCash: "ലഭ്യമായ പണ കരുതൽ",
    receivables: "ലഭിക്കാനുള്ള കുടിശ്ശിക",
    burnRate: "പ്രതിമാസ ചെലവ് വേഗത",
    netRunway: "30-ദിവസത്തെ റൺവേ",
    daysBuffer: "ദിവസങ്ങളുടെ സുരക്ഷ",
    pendingInvoices: "തീർപ്പുകൽപ്പിക്കാത്ത ബില്ലുകൾ",
    solvencyScore: "ധനകാര്യ ആരോഗ്യ സ്കോർ",
    saveChanges: "മാറ്റങ്ങൾ സംരക്ഷിക്കുക",
    companyProfile: "കമ്പനി വിവരങ്ങളും ലക്ഷ്യങ്ങളും",
    languageOption: "പ്രാദേശിക ഭാഷാ തിരഞ്ഞെടുപ്പ്",
    languageSub: "നിങ്ങളുടെ സാമ്പത്തിക ഡാഷ്‌ബോർഡിനായി ഇഷ്ടപ്പെട്ട ഭാഷ തിരഞ്ഞെടുക്കുക",
    currentLanguage: "സജീവ ഭാഷ",
    selectLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    saveLanguage: "ഭാഷ പ്രയോഗിക്കുക",
    resetData: "ഡാറ്റ പുനഃസജ്ജമാക്കുക",
    activeTwin: "സജീവ ട്വിൻ എഞ്ചിൻ",
    days: "ദിവസങ്ങൾ",
  },
  or: {
    dashboard: "ଡ୍ୟାସବୋର୍ଡ",
    cashFlow: "କ୍ୟାଶ ଫ୍ଲୋ ଟ୍ୱିନ୍",
    invoices: "ଚାଲାଣ ଓ ବିଲ୍ (Invoices)",
    expenses: "ମାସିକ ଖର୍ଚ୍ଚ ଓ ବର୍ଣ୍ଣ",
    customers: "ଗ୍ରାହକ ଓ ବିପଦ ବିଶ୍ଳେଷଣ",
    forecast: "୯୦-ଦିନିଆ ପୂର୍ବାନୁମାନ",
    simulator: "ଶକ୍ ସିମ୍ୟୁଲେଟର",
    financing: "MSME ଋଣ ଓ ଆର୍ଥିକ ସହାୟତା",
    gst: "ଜିଏସଟି ଓ ଟ୍ୟାକ୍ସ (GST)",
    payroll: "କର୍ମଚାରୀ ଓ ବେତନ (Payroll)",
    reports: "ଆର୍ଥିକ ରିପୋର୍ଟ",
    settings: "ସେଟିଙ୍ଗ୍ସ (Settings)",
    logout: "ଲଗ ଆଉଟ୍",
    quickAdd: "+ ଶୀଘ୍ର ଯୋଡନ୍ତୁ",
    quickSearch: "ସନ୍ଧାନ କରନ୍ତୁ...",
    askAi: "AI କୁ ପଚାରନ୍ତୁ",
    notifications: "ସୂଚନା ଓ ଚେତାବନୀ",
    liquidCash: "ଉପଲବ୍ଧ ନଗଦ ଟଙ୍କା",
    receivables: "ବାକି ପାଉଣା",
    burnRate: "ମାସିକ ଖର୍ଚ୍ଚ ବେଗ",
    netRunway: "୩୦-ଦିନିଆ ନେଟ୍ ରନୱେ",
    daysBuffer: "ଦିନର ବଫର",
    pendingInvoices: "ବାକି ବିଲ୍",
    solvencyScore: "ଆର୍ଥିକ ସ୍ୱାସ୍ଥ୍ୟ ସ୍କୋର",
    saveChanges: "ସଂରକ୍ଷଣ କରନ୍ତୁ",
    companyProfile: "କମ୍ପାନୀ ପ୍ରୋଫାଇଲ ଓ ଲକ୍ଷ୍ୟ",
    languageOption: "ଆଞ୍ଚଳିକ ଭାଷା ଚୟନ",
    languageSub: "ଡ୍ୟାସବୋର୍ଡ ପାଇଁ ଆପଣଙ୍କ ପସନ୍ଦର ଆଞ୍ଚଳିକ ଭାଷା ବାଛନ୍ତୁ",
    currentLanguage: "ସକ୍ରିୟ ଭାଷା",
    selectLanguage: "ଭାଷା ବାଛନ୍ତୁ",
    saveLanguage: "ଭାଷା ପ୍ରୟୋଗ କରନ୍ତୁ",
    resetData: "ଡାଟା ରିସେଟ୍ କରନ୍ତୁ",
    activeTwin: "ସକ୍ରିୟ ଟ୍ୱିନ୍ ଇଞ୍ଜିନ",
    days: "ଦିନ",
  },
  as: {
    dashboard: "ডেশ্বব’ৰ্ড",
    cashFlow: "কেশ্ব ফ্লো টুইন",
    invoices: "চালান আৰু বিল (Invoices)",
    expenses: "মাহিলী খৰচ আৰু বাৰ্ন",
    customers: "গ্ৰাহক আৰু আশংকা",
    forecast: "৯০-দিনীয়া পূৰ্বানুমান",
    simulator: "শ্বক চিমুলেটৰ",
    financing: "MSME ঋণ আৰু বিত্তীয় সাহায্য",
    gst: "জিএছটি আৰু কৰ (GST)",
    payroll: "কৰ্মচাৰী আৰু দৰমহা (Payroll)",
    reports: "বিত্তীয় প্ৰতিবেদন",
    settings: "ছেটিংছ (Settings)",
    logout: "লগ আউট",
    quickAdd: "+ দ্ৰুত যোগ কৰক",
    quickSearch: "সন্ধান কৰক...",
    askAi: "AI ক সোধক",
    notifications: "জাননী আৰু সতৰ্কবাণী",
    liquidCash: "মজুত নগদ ধন",
    receivables: "প্ৰাপ্য ধন",
    burnRate: "মাহিলী ব্যয়ৰ গতি",
    netRunway: "৩০-দিনীয়া ৰাণৱে",
    daysBuffer: "দিনৰ সুৰক্ষা বাফাৰ",
    pendingInvoices: "বাকী থকা বিল",
    solvencyScore: "বিত্তীয় স্বাস্থ্য স্কোৰ",
    saveChanges: "সংৰক্ষণ কৰক",
    companyProfile: "কোম্পানীৰ বিৱৰণ আৰু লক্ষ্য",
    languageOption: "আঞ্চলিক ভাষা বাছনি",
    languageSub: "ডেশ্বব’ৰ্ডৰ বাবে আপোনাৰ পছন্দৰ আঞ্চলিক ভাষা বাছক",
    currentLanguage: "বৰ্তমান ভাষা",
    selectLanguage: "ভাষা বাছনি কৰক",
    saveLanguage: "ভাষা প্ৰয়োগ কৰক",
    resetData: "তথ্য ৰিছেট কৰক",
    activeTwin: "সক্ৰিয় টুইন",
    days: "দিন",
  },
  ur: {
    dashboard: "ڈیش بورڈ",
    cashFlow: "کیش فلو ڈیجیٹل ٹوئن",
    invoices: "انوائسز و بلز (Invoices)",
    expenses: "ماہانہ اخراجات و برن",
    customers: "گاہک و رسک کا تخمینہ",
    forecast: "90-روزہ پیش گوئی",
    simulator: "شاک سیمولیٹر (What-If)",
    financing: "ایم ایس ایم ای فنانسنگ و قرضے",
    gst: "جی ایس ٹی اور ٹیکس (GST)",
    payroll: "ملازمین اور تنخواہیں (Payroll)",
    reports: "مالیاتی رپورٹس",
    settings: "ترتیبات (Settings)",
    logout: "لاگ آؤٹ",
    quickAdd: "+ فوری شامل کریں",
    quickSearch: "تلاش کریں...",
    askAi: "اے آئی ٹوئن سے پوچھیں",
    notifications: "اطلاعات و الرٹس",
    liquidCash: "موجودہ نقد رقم (Liquid Cash)",
    receivables: "واجب الادا وصولیاں",
    burnRate: "ماہانہ خرچ کی رفتار",
    netRunway: "30-روزہ کیش رن وے",
    daysBuffer: "دنوں کا بفر",
    pendingInvoices: "زیر التوا بل",
    solvencyScore: "مالیاتی صحت کا اسکور",
    saveChanges: "تبدیلیاں محفوظ کریں",
    companyProfile: "کمپنی پروفائل اور اہداف",
    languageOption: "علاقائی زبان کا انتخاب",
    languageSub: "مالیاتی ڈیش بورڈ کے لیے اپنی پسندیدہ زبان منتخب کریں",
    currentLanguage: "فعال زبان",
    selectLanguage: "زبان منتخب کریں",
    saveLanguage: "زبان لاگو کریں",
    resetData: "ڈیٹا ری سیٹ کریں",
    activeTwin: "فعال ٹوئن انجن",
    days: "دن",
  },
  bho: {
    dashboard: "डैशबोर्ड",
    cashFlow: "कैश फ्लो ट्विन",
    invoices: "चालान आ बिल (Invoices)",
    expenses: "महिनावार खरचा आ बर्न",
    customers: "ग्राहक आ जोखिम",
    forecast: "90-दिन के अनुमान",
    simulator: "शॉक सिमुलेटर",
    financing: "एमएसएमई कर्जा आ लोन",
    gst: "जीएसटी आ टैक्स (GST)",
    payroll: "मजदूर आ वेतन (Payroll)",
    reports: "वित्तीय रिपोर्ट",
    settings: "सेटिंग्स",
    logout: "बाहर निकलीं (Logout)",
    quickAdd: "+ जल्दी जोड़ीं",
    quickSearch: "खोजीं...",
    askAi: "AI से पूछीं",
    notifications: "सूचना आ अलर्ट",
    liquidCash: "हाथ में नकद रुपिया",
    receivables: "बाकी वसूली",
    burnRate: "मासिक खरच के तेजी",
    netRunway: "30-दिन के रनवे",
    daysBuffer: "दिन के बफर",
    pendingInvoices: "अटकल चालान",
    solvencyScore: "कारोबारी सेहत स्कोर",
    saveChanges: "बदलाव सहेजीं",
    companyProfile: "कंपनी प्रोफाइल आ लक्ष्य",
    languageOption: "क्षेत्रीय भाषा चुनीं",
    languageSub: "डैशबोर्ड खातिर आपन क्षेत्रीय भाषा चुनीं",
    currentLanguage: "चालू भाषा",
    selectLanguage: "भाषा चुनीं",
    saveLanguage: "भाषा लागू करीं",
    resetData: "डेटा साफ़ करीं",
    activeTwin: "एक्टिव डिजिटल ट्विन",
    days: "दिन",
  },
  mai: {
    dashboard: "डैशबोर्ड",
    cashFlow: "कैश फ्लो ट्विन",
    invoices: "चालान आ बिल",
    expenses: "मासिक खर्च आ बर्न",
    customers: "ग्राहक आ जोखिम",
    forecast: "९०-दिवसीय पूर्वानुमान",
    simulator: "शॉक सिमुलेटर",
    financing: "एमएसएमई लोन आ वित्त",
    gst: "जीएसटी आ कर (GST)",
    payroll: "कर्मचारी आ वेतन (Payroll)",
    reports: "वित्तीय रिपोर्ट",
    settings: "सेटिंग्स",
    logout: "लॉग आउट",
    quickAdd: "+ झटपट जोड़ू",
    quickSearch: "खोजू...",
    askAi: "AI सँ पूछू",
    notifications: "सूचना आ चेतावनी",
    liquidCash: "उपलब्ध नकद राशि",
    receivables: "बाकी वसूली",
    burnRate: "मासिक खर्चक गति",
    netRunway: "३०-दिनक रनवे",
    daysBuffer: "दिनक सुरक्षा बफर",
    pendingInvoices: "लंबित बिल",
    solvencyScore: "आर्थिक स्वास्थ्य स्कोर",
    saveChanges: "सहेजू (Save)",
    companyProfile: "कंपनी विवरण आ लक्ष्य",
    languageOption: "प्रांतीय भाषा चयन",
    languageSub: "अपन मनपसंद क्षेत्रीय भाषा चुनी",
    currentLanguage: "वर्तमान भाषा",
    selectLanguage: "भाषा चुनू",
    saveLanguage: "लागू करू",
    resetData: "डेटा रीसेट करू",
    activeTwin: "सक्रिय ट्विन इंजन",
    days: "दिन",
  },
  kok: {
    dashboard: "डॅशबोर्ड",
    cashFlow: "कॅश फ्लो ट्विन",
    invoices: "बिलीं आनी इनव्हॉईस",
    expenses: "म्हयन्याचो खर्च आनी बर्न",
    customers: "ग्राहक आनी जोखीम",
    forecast: "९० दिसांचो अदमास",
    simulator: "शॉक सिम्युलेटर",
    financing: "एमएसएमई रीण आनी अर्थसहाय्य",
    gst: "जीएसटी आनी कर (GST)",
    payroll: "कामगार आनी पगार (Payroll)",
    reports: "आर्थिक अहवाल",
    settings: "सेटिंग्ज",
    logout: "भायर सरात (Logout)",
    quickAdd: "+ बेगीन जोडात",
    quickSearch: "सोदात...",
    askAi: "AI क विचारात",
    notifications: "मुलखावे आनी अलर्ट",
    liquidCash: "हातातली रोकड शिल्लक",
    receivables: "येवपाची बाकी",
    burnRate: "मासिक खर्चाची गती",
    netRunway: "३० दिसांचो रनवे",
    daysBuffer: "दिसांचो बफर",
    pendingInvoices: "उरिल्लीं बिलीं",
    solvencyScore: "आर्थिक भलायकी स्कोर",
    saveChanges: "बदल सांबाळात",
    companyProfile: "कंपनी तपशील आनी ध्येयां",
    languageOption: "प्रादेशीक भास निवड",
    languageSub: "डॅशबोर्डाखातीर तुमची आवडीची भास वेचात",
    currentLanguage: "सध्याची भास",
    selectLanguage: "भास वेचात",
    saveLanguage: "भास लागू करात",
    resetData: "डेटा रिसेट करात",
    activeTwin: "सक्रीय ट्विन इंजिन",
    days: "दीस",
  },
  sd: {
    dashboard: "ڊيش بورڊ",
    cashFlow: "ڪيش فلو ٽوئن",
    invoices: "بل ۽ انوائسز (Invoices)",
    expenses: "مهيني جا خرچ ۽ برن",
    customers: "گراهڪ ۽ خطرو (Risk)",
    forecast: "90-ڏينهن جي اڳڪٿي",
    simulator: "شاڪ سموليٽر",
    financing: "MSME قرض ۽ فنانس",
    gst: "جي ايس ٽي ۽ ٽيڪس (GST)",
    payroll: "ملازم ۽ پگهارون (Payroll)",
    reports: "مالياتي رپورٽون",
    settings: "سيٽنگون",
    logout: "لاگ آئوٽ",
    quickAdd: "+ فوري شامل ڪريو",
    quickSearch: "ڳوليو...",
    askAi: "AI کان پڇو",
    notifications: "اطلاع ۽ الرٽس",
    liquidCash: "هٿ ۾ روڪ رقم",
    receivables: "اوڳاڙڻ جا باقي پئسا",
    burnRate: "مهيني جي خرچ جي رفتار",
    netRunway: "30-ڏينهن جو رن وي",
    daysBuffer: "ڏينهن جو بفر",
    pendingInvoices: "باقي بل",
    solvencyScore: "مالياتي صحت اسڪور",
    saveChanges: "تبديليون محفوظ ڪريو",
    companyProfile: "ڪمپني پروفائل ۽ مقصد",
    languageOption: "علائقائي ٻولي جي چونڊ",
    languageSub: "ڊيش بورڊ لاءِ پنهنجي پسند جي ٻولي چونڊيو",
    currentLanguage: "موجوده ٻولي",
    selectLanguage: "ٻولي چونڊيو",
    saveLanguage: "ٻولي لاڳو ڪريو",
    resetData: "ڊيٽا صاف ڪريو",
    activeTwin: "فعال ٽوئن",
    days: "ڏينهن",
  },
  ne: {
    dashboard: "ड्यासबோர्ड",
    cashFlow: "नगद प्रवाह (Cash Flow) ट्विन",
    invoices: "बिल तथा इनभ्वाइस",
    expenses: "मासिक खर्च र बर्न",
    customers: "ग्राहक र जोखिम विश्लेषण",
    forecast: "९०-दिने प्रक्षेपण",
    simulator: "शक सिम्युलेटर (What-If)",
    financing: "MSME ऋण तथा वित्तीय सहायता",
    gst: "कर तथा जीएसटी प्रणाली",
    payroll: "कर्मचारी तथा तलब (Payroll)",
    reports: "वित्तीय प्रतिवेदन",
    settings: "सेटिङहरू (Settings)",
    logout: "लग आउट",
    quickAdd: "+ तुरुन्त थप्नुहोस्",
    quickSearch: "खोज्नुहोस्...",
    askAi: "AI लाई सोध्नुहोस्",
    notifications: "सूचनाहरू र चेतावनी",
    liquidCash: "उपलब्ध नगद मौज्दात",
    receivables: "उठाउन बाँकी रकम",
    burnRate: "मासिक खर्च गति",
    netRunway: "३०-दिने नगद रनवे",
    daysBuffer: "दिनहरूको सुरक्षा बफर",
    pendingInvoices: "बाँकी बिलहरू",
    solvencyScore: "वित्तीय स्वास्थ्य स्कोर",
    saveChanges: "परिवर्तनहरू बचत गर्नुहोस्",
    companyProfile: "कम्पनी विवरण र लक्ष्य",
    languageOption: "क्षेत्रीय भाषा छनोट",
    languageSub: "ड्यासबोर्डको लागि आफ्नो मनपर्ने क्षेत्रीय भाषा छान्नुहोस्",
    currentLanguage: "हालको सक्रिय भाषा",
    selectLanguage: "भाषा छनोट गर्नुहोस्",
    saveLanguage: "भाषा लागू गर्नुहोस्",
    resetData: "सम्पूर्ण डेटा रिसेट गर्नुहोस्",
    activeTwin: "सक्रिय ट्विन इन्जिन",
    days: "दिनहरू",
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem("fintwin_language") || "en";
  });

  const changeLanguage = (langCode) => {
    if (TRANSLATIONS[langCode]) {
      setCurrentLang(langCode);
      localStorage.setItem("fintwin_language", langCode);
    }
  };

  const t = (key, fallback = "") => {
    const langDict = TRANSLATIONS[currentLang] || TRANSLATIONS.en;
    return langDict[key] || TRANSLATIONS.en[key] || fallback || key;
  };

  const activeLanguageMeta =
    SUPPORTED_LANGUAGES.find((l) => l.id === currentLang) || SUPPORTED_LANGUAGES[0];

  return (
    <LanguageContext.Provider
      value={{
        currentLang,
        changeLanguage,
        t,
        supportedLanguages: SUPPORTED_LANGUAGES,
        activeLanguageMeta,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
